[tool.poetry]
name = "quoridor-zoo"
version = "0.1.0"
description = ""
authors = ["KonstFed <konstfed12@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = ">=3.9,<3.13"
pettingzoo = "^1.25.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
